### ISSUE TITLE
JS: Error: Css styling failed: missing '{'

### ISSUE THREAD

**Issue by gbaldeck** [toddanglin/nativescript-dev-sass#45] opened 2017-10-02 14:53 UTC
After installing the nativescript-dev-sass plugin, I renamed the app.css file in my /app directory to app.scss, so that I could write sass in the file. The file contained one import statement, so I changed it from:
`@import 'nativescript-theme-core/css/sky.css';`
to
`@import '~nativescript-theme-core/css/sky.css'; //notice the tilde`

Using the tilde as mentioned in the readme of the nativescript-dev-sass repository.

When I run `tns run android` I get the following error when my app starts:
JS: Error: Css styling failed: Error: /data/data/io.myapp.app/files/app/app.css:1:97: missing '{'

The resulting app.css file that is compiled from app.scss has the below line:
`@import url(C:\my_workspace\myapp\node_modules\nativescript-theme-core\css\sky.css)`

Column 97 of that line, as specified in the error message, is the one right after the closing parenthesis ), and there really shouldn't be a { there. So I have no idea why it's saying the the { is missing.

What can I do to fix this?

**Comment by zbranzov** [comment] 2017-12-04 13:00
@gbaldeck 
I was unable to reproduce your error but I want to note that when importing css to sass you have to remove the file extension. E.g. 
@import '~nativescript-theme-core/css/sky';

I'm closing this issue, but if you still find it relevant please add more details how we can reproduce the case and reopen the issue.

**Closed as completed by zbranzov** 2017-12-04 13:00 UTC

**Comment by bhavincb** [comment] 2018-02-22 07:57
i was getting same error that
JS: Error: Css styling failed: Error: /app.css:1:97: missing '{'

so i had recreated the app

`tns create HelloWorld --template nativescript-template-tutorial`
`tns install sass`
`npm install -g node-sass`
after using above commands. i had renamed app.css to app.scss and added below code
`@import "~nativescript-theme-core/css/sky";`
now it gives below error

Error: File to import not found or unreadable: E:\nativescript\HelloWorld\
node_modules\nativescript-theme-core\css\sky.
       Parent style sheet: E:/nativescript/HelloWorld/app/app.scss
        on line 1 of app/app.scss
>> @import "~nativescript-theme-core/css/sky";


anf if i use below code in app.scss
`@import "~nativescript-theme-core/css/sky.css";`
then it generates app.css with full absolute  path to sky.css

`@import url(E:\nativescript\HelloWorld\node_modules\nativescript-theme-core\css\sky.css)
`

what can i do to fix this?

**Comment by rynop** [comment] 2019-01-10 21:29
I fixed this problem by clearing out all my css files and following the [SASS usage](https://docs.nativescript.org/ui/theme#sass-usage) directions
